//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alphora.Dataphor.Dataphoria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class DataphoriaException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alphora.Dataphor.Dataphoria.DataphoriaException", typeof(DataphoriaException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename node.  A node with that name already exists..
        /// </summary>
        internal static string _124107 {
            get {
                return ResourceManager.GetString("124107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is an invalid identifier or a reserved word..
        /// </summary>
        internal static string _124109 {
            get {
                return ResourceManager.GetString("124109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register Window Message ({0})..
        /// </summary>
        internal static string _124110 {
            get {
                return ResourceManager.GetString("124110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type ({0}) is not defined, or there is no default designer specified for it..
        /// </summary>
        internal static string _124111 {
            get {
                return ResourceManager.GetString("124111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no designers associated with document type ({0})..
        /// </summary>
        internal static string _124112 {
            get {
                return ResourceManager.GetString("124112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form designer does not support multiple document ancestors..
        /// </summary>
        internal static string _124113 {
            get {
                return ResourceManager.GetString("124113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live edits are only allowed for expressions that load documents..
        /// </summary>
        internal static string _124114 {
            get {
                return ResourceManager.GetString("124114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML document: {0}.
        /// </summary>
        internal static string _124115 {
            get {
                return ResourceManager.GetString("124115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type ({0}) cannot be edited using a live designer..
        /// </summary>
        internal static string _124116 {
            get {
                return ResourceManager.GetString("124116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open help file ({0}).  It may have not been installed..
        /// </summary>
        internal static string _124117 {
            get {
                return ResourceManager.GetString("124117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is already being designed..
        /// </summary>
        internal static string _124118 {
            get {
                return ResourceManager.GetString("124118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one designer is allowed to be open on a form..
        /// </summary>
        internal static string _124120 {
            get {
                return ResourceManager.GetString("124120", resourceCulture);
            }
        }
    }
}
