//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alphora.Dataphor.Dataphoria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alphora.Dataphor.Dataphoria.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Analyzer_AttributeTable_AttributeTitle {
            get {
                return ResourceManager.GetString("Analyzer.AttributeTable.AttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Analyzer_AttributeTable_ValueTitle {
            get {
                return ResourceManager.GetString("Analyzer.AttributeTable.ValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Details.
        /// </summary>
        internal static string Analyzer_DetailNodeTitle {
            get {
                return ResourceManager.GetString("Analyzer.DetailNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        internal static string Analyzer_DetailsColumnTitle {
            get {
                return ResourceManager.GetString("Analyzer.DetailsColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Analyzer_MainSurfaceTitle {
            get {
                return ResourceManager.GetString("Analyzer.MainSurfaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Tree.
        /// </summary>
        internal static string Analyzer_PlanNodeTitle {
            get {
                return ResourceManager.GetString("Analyzer.PlanNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Analyzer_TextDetailTitle {
            get {
                return ResourceManager.GetString("Analyzer.TextDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script is currently being executed.  The script execution will be cancelled in order for the editor to close..
        /// </summary>
        internal static string AttemptingToCloseWhileExecuting {
            get {
                return ResourceManager.GetString("AttemptingToCloseWhileExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Execution?.
        /// </summary>
        internal static string AttemptingToCloseWhileExecutingCaption {
            get {
                return ResourceManager.GetString("AttemptingToCloseWhileExecutingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup Catalog.
        /// </summary>
        internal static string BackupCatalogMenuText {
            get {
                return ResourceManager.GetString("BackupCatalogMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog backup completed successfully..
        /// </summary>
        internal static string BackupCatalogSuccess {
            get {
                return ResourceManager.GetString("BackupCatalogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Schemas....
        /// </summary>
        internal static string ComparingSchema {
            get {
                return ResourceManager.GetString("ComparingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ustomize....
        /// </summary>
        internal static string CustomizeMenuText {
            get {
                return ResourceManager.GetString("CustomizeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataphoria.
        /// </summary>
        internal static string DataphoriaTitle {
            get {
                return ResourceManager.GetString("DataphoriaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;elete.
        /// </summary>
        internal static string DeleteMenuItemText {
            get {
                return ResourceManager.GetString("DeleteMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Objects.
        /// </summary>
        internal static string DependentObjects {
            get {
                return ResourceManager.GetString("DependentObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        internal static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details.
        /// </summary>
        internal static string DetailsMenuItemText {
            get {
                return ResourceManager.GetString("DetailsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disconnect.
        /// </summary>
        internal static string DisconnectMenuText {
            get {
                return ResourceManager.GetString("DisconnectMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string DocumentModifiedCaption {
            get {
                return ResourceManager.GetString("DocumentModifiedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document (&apos;{0}&apos;) was modified, save changes?.
        /// </summary>
        internal static string DocumentModifiedText {
            get {
                return ResourceManager.GetString("DocumentModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ancel.
        /// </summary>
        internal static string DropMenu_Cancel {
            get {
                return ResourceManager.GetString("DropMenu.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string DropMenu_Copy {
            get {
                return ResourceManager.GetString("DropMenu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Move.
        /// </summary>
        internal static string DropMenu_Move {
            get {
                return ResourceManager.GetString("DropMenu.Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;dit Copy....
        /// </summary>
        internal static string EditCopyMenuText {
            get {
                return ResourceManager.GetString("EditCopyMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        internal static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Schema.
        /// </summary>
        internal static string EditSchemaMenuText {
            get {
                return ResourceManager.GetString("EditSchemaMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportSaveDialogTitle {
            get {
                return ResourceManager.GetString("ExportSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string FileOpenTitle {
            get {
                return ResourceManager.GetString("FileOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found..
        /// </summary>
        internal static string FindTextNotFound {
            get {
                return ResourceManager.GetString("FindTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online help file is currently loading.  Online help will be available when it is completely loaded..
        /// </summary>
        internal static string HelpLoading {
            get {
                return ResourceManager.GetString("HelpLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Cannot edit while registered).
        /// </summary>
        internal static string LibraryNode_CannotEditWhileRegistered {
            get {
                return ResourceManager.GetString("LibraryNode.CannotEditWhileRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Designer.
        /// </summary>
        internal static string LiveDesigner {
            get {
                return ResourceManager.GetString("LiveDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Designer....
        /// </summary>
        internal static string NewDesignerMenuText {
            get {
                return ResourceManager.GetString("NewDesignerMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add....
        /// </summary>
        internal static string ObjectTree_AddMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.AddMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach &amp;Libraries....
        /// </summary>
        internal static string ObjectTree_AttachLibrariesMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.AttachLibrariesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;ttach....
        /// </summary>
        internal static string ObjectTree_AttachMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.AttachMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse.
        /// </summary>
        internal static string ObjectTree_BrowseMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.BrowseMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Customization.
        /// </summary>
        internal static string ObjectTree_CustomizeMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.CustomizeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete....
        /// </summary>
        internal static string ObjectTree_DeleteMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.DeleteMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;erive....
        /// </summary>
        internal static string ObjectTree_DeriveMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.DeriveMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De&amp;tach....
        /// </summary>
        internal static string ObjectTree_DetachMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.DetachMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Drop....
        /// </summary>
        internal static string ObjectTree_DropMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.DropMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        internal static string ObjectTree_EditMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em&amp;it Create Script.
        /// </summary>
        internal static string ObjectTree_EmitCreateScriptMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.EmitCreateScriptMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emi&amp;t Drop Script.
        /// </summary>
        internal static string ObjectTree_EmitDropScriptMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.EmitDropScriptMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Execute.
        /// </summary>
        internal static string ObjectTree_ExecuteMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ExecuteMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string ObjectTree_GroupsNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.GroupsNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Without Reconci&amp;liation.
        /// </summary>
        internal static string ObjectTree_LoadMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.LoadMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage &amp;Groups.
        /// </summary>
        internal static string ObjectTree_ManageGroupsText {
            get {
                return ResourceManager.GetString("ObjectTree.ManageGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage &amp;Users.
        /// </summary>
        internal static string ObjectTree_ManageUsersText {
            get {
                return ResourceManager.GetString("ObjectTree.ManageUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string ObjectTree_OpenMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.OpenMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Register Script.
        /// </summary>
        internal static string ObjectTree_OpenRegisterScriptMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.OpenRegisterScriptMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Script....
        /// </summary>
        internal static string ObjectTree_OpenScriptMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.OpenScriptMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;With....
        /// </summary>
        internal static string ObjectTree_OpenWithMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.OpenWithMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Automatic.
        /// </summary>
        internal static string ObjectTree_ReconciliationModeAutomaticMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ReconciliationModeAutomaticMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Command.
        /// </summary>
        internal static string ObjectTree_ReconciliationModeCommandMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ReconciliationModeCommandMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation &amp;Mode.
        /// </summary>
        internal static string ObjectTree_ReconciliationModeMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ReconciliationModeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;None.
        /// </summary>
        internal static string ObjectTree_ReconciliationModeNoneMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ReconciliationModeNoneMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Startup.
        /// </summary>
        internal static string ObjectTree_ReconciliationModeStartupMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ReconciliationModeStartupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string ObjectTree_RefreshMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.RefreshMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Register With Reconciliation.
        /// </summary>
        internal static string ObjectTree_RegisterMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.RegisterMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string ObjectTree_RolesNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.RolesNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string ObjectTree_SchemaNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.SchemaNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script &amp;Changes....
        /// </summary>
        internal static string ObjectTree_ScriptChangesText {
            get {
                return ResourceManager.GetString("ObjectTree.ScriptChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string ObjectTree_SecurityNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.SecurityNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set As Current.
        /// </summary>
        internal static string ObjectTree_SetAsCurrentMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.SetAsCurrentMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Generated Objects.
        /// </summary>
        internal static string ObjectTree_ShowGeneratedObjects {
            get {
                return ResourceManager.GetString("ObjectTree.ShowGeneratedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show.
        /// </summary>
        internal static string ObjectTree_ShowMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ShowMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show System Objects.
        /// </summary>
        internal static string ObjectTree_ShowSystemObjects {
            get {
                return ResourceManager.GetString("ObjectTree.ShowSystemObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string ObjectTree_StartMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.StartMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string ObjectTree_TableListNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.TableListNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister Without Reconci&amp;liation.
        /// </summary>
        internal static string ObjectTree_UnloadMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.UnloadMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un&amp;register With Reconciliation.
        /// </summary>
        internal static string ObjectTree_UnregisterMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.UnregisterMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U&amp;pgrade.
        /// </summary>
        internal static string ObjectTree_UpgradeLibraryMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.UpgradeLibraryMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upgrades....
        /// </summary>
        internal static string ObjectTree_UpgradesMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.UpgradesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string ObjectTree_UsersNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.UsersNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View De&amp;pendencies.
        /// </summary>
        internal static string ObjectTree_ViewDependencies {
            get {
                return ResourceManager.GetString("ObjectTree.ViewDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vie&amp;w Dependents.
        /// </summary>
        internal static string ObjectTree_ViewDependents {
            get {
                return ResourceManager.GetString("ObjectTree.ViewDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ObjectTree_ViewListNodeText {
            get {
                return ResourceManager.GetString("ObjectTree.ViewListNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View....
        /// </summary>
        internal static string ObjectTree_ViewMenuText {
            get {
                return ResourceManager.GetString("ObjectTree.ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open File....
        /// </summary>
        internal static string OpenFileMenuText {
            get {
                return ResourceManager.GetString("OpenFileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File &amp;With....
        /// </summary>
        internal static string OpenFileWithMenuText {
            get {
                return ResourceManager.GetString("OpenFileWithMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another designer is editing this document.  Close the existing designer and open the document using the selected designer?.
        /// </summary>
        internal static string OtherDesignerOpen {
            get {
                return ResourceManager.GetString("OtherDesignerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is already open.
        /// </summary>
        internal static string OtherDesignerOpenTitle {
            get {
                return ResourceManager.GetString("OtherDesignerOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Prepared Successfully
        ///Prepare Time: {0} (Compile Time: {1} Optimize Time: {2} Bind Time: {3}).
        /// </summary>
        internal static string PrepareSuccessful {
            get {
                return ResourceManager.GetString("PrepareSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Query....
        /// </summary>
        internal static string ProcessingQuery {
            get {
                return ResourceManager.GetString("ProcessingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rename.
        /// </summary>
        internal static string RenameMenuItemText {
            get {
                return ResourceManager.GetString("RenameMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurrence(s) have been replaced..
        /// </summary>
        internal static string ReplacementsPerformed {
            get {
                return ResourceManager.GetString("ReplacementsPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Objects.
        /// </summary>
        internal static string RequiredObjects {
            get {
                return ResourceManager.GetString("RequiredObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}: {1}&quot; already exists.  Do you want to replace it?.
        /// </summary>
        internal static string SaveAsDialogReplaceText {
            get {
                return ResourceManager.GetString("SaveAsDialogReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Document.
        /// </summary>
        internal static string SaveAsDocumentFormTitle {
            get {
                return ResourceManager.GetString("SaveAsDocumentFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Catalog.
        /// </summary>
        internal static string SaveCatalogMenuText {
            get {
                return ResourceManager.GetString("SaveCatalogMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog save completed successfully..
        /// </summary>
        internal static string SaveCatalogSuccess {
            get {
                return ResourceManager.GetString("SaveCatalogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string SaveChangesCaption {
            get {
                return ResourceManager.GetString("SaveChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As File.
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Designer.
        /// </summary>
        internal static string SchemaFormTitle {
            get {
                return ResourceManager.GetString("SchemaFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Analysis Failed.
        /// </summary>
        internal static string ScriptAnalyzeFailed {
            get {
                return ResourceManager.GetString("ScriptAnalyzeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Analyzed Successfully.
        /// </summary>
        internal static string ScriptAnalyzeSuccessful {
            get {
                return ResourceManager.GetString("ScriptAnalyzeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Failed.
        /// </summary>
        internal static string ScriptFailed {
            get {
                return ResourceManager.GetString("ScriptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script injected into library {0} as upgrade version {1}..
        /// </summary>
        internal static string ScriptInjected {
            get {
                return ResourceManager.GetString("ScriptInjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Prepare Failed.
        /// </summary>
        internal static string ScriptPrepareFailed {
            get {
                return ResourceManager.GetString("ScriptPrepareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Prepared Successfully.
        /// </summary>
        internal static string ScriptPrepareSuccessful {
            get {
                return ResourceManager.GetString("ScriptPrepareSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Executed Successfully.
        /// </summary>
        internal static string ScriptSuccessful {
            get {
                return ResourceManager.GetString("ScriptSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a designer....
        /// </summary>
        internal static string SelectDesigner {
            get {
                return ResourceManager.GetString("SelectDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a target node for move or copy operation..
        /// </summary>
        internal static string SelectTargetNode {
            get {
                return ResourceManager.GetString("SelectTargetNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string UnspecifiedCategory {
            get {
                return ResourceManager.GetString("UnspecifiedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string UntitledDocumentDescription {
            get {
                return ResourceManager.GetString("UntitledDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upgrade Libraries....
        /// </summary>
        internal static string UpgradeLibrariesMenuText {
            get {
                return ResourceManager.GetString("UpgradeLibrariesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries upgraded successfully..
        /// </summary>
        internal static string UpgradeLibrariesSuccess {
            get {
                return ResourceManager.GetString("UpgradeLibrariesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library upgraded successfully..
        /// </summary>
        internal static string UpgradeLibrarySuccess {
            get {
                return ResourceManager.GetString("UpgradeLibrarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Canceled..
        /// </summary>
        internal static string UserAbort {
            get {
                return ResourceManager.GetString("UserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View Log....
        /// </summary>
        internal static string ViewLogMenuText {
            get {
                return ResourceManager.GetString("ViewLogMenuText", resourceCulture);
            }
        }
    }
}
