= Architectural Overview
:author: Alphora
:doctype: book

:icons:
:data-uri:
:lang: en
:encoding: iso-8859-1

[[DUGP1ProductTour-ArchitecturalOverview]]
== Summary

Dataphor is an application development platform designed to streamline
the process of designing, developing, and maintaining software
applications. In order to realize these goals, the architecture of the
Dataphor product is segmented into three main layers: the Physical
Layer, the Logical Layer, and the Presentation Layer. Each layer is
responsible for a specific set of functionality within the overall
product. The Physical Layer is responsible for managing the persistent
data of the applications. The Presentation Layer is responsible for
managing the interaction with users of the applications. The Logical
Layer is responsible for providing the actual descriptions of the
applications.

The following diagram depicts these layers:

image::../Images/Dataphor%20Overall%20-%20Simplified.svg[Dataphor Logo]

This diagram shows the components of the Dataphor architecture, and the
interactions between them. At the center of the architecture is the
Dataphor Data Access Engine (DAE), or Dataphor Server. The Dataphor
Server exposes application schemas that are consumed by Windows-based,
Web-based and other clients, and manages the coordination of the
presentation layer data retrieval and manipulation requests with the
various storage devices in the physical layer.

Dataphor PlatformComponentsDataphorComponentsThe concrete components of
the Dataphor product are then:

* Dataphor Server
+
The Dataphor Application platform which exposes the capabilities and
services required to develop and run Dataphor Applications.
* Frontend Server
+
A library of routines and services deployed within a Dataphor Server
enabling the presentation layer of a Dataphor Application.
* Dataphoria
+
An Integrated Development Environment (IDE) for developing, testing, and
administering Dataphor Applications.
* Frontend Clients
+
A set of "thin-client" software components that manage the presentation
layer for their respective platforms. The Dataphor product ships with a
Microsoft Windows-based client, and a Web client. Additional clients can
be developed as necessary.

These components together provide the services and functionality
required by the Dataphor platform to enable the declarative approach.
The resulting paradigm is called __Automated Application Development (AAD)__. Each of these
components are introduced in the following sections. Complete
information on using each component is then provided in the subsequent
chapters of this manual.

The Dataphor product is built using the Microsoft .NET Framework. The
.NET Framework provides a component library, a set of compilers, and an
execution runtime. The Dataphor platform can be altered and extended
using capabilities of the .NET Framework such as dynamic class loading.
