= Book Publishing (Microsoft Pubs) Tutorial
:author: Alphora
:doctype: book
:icons:
:data-uri:
:lang: en
:encoding: iso-8859-1

== Summary

This tutorial makes use of the pubs database supplied with the MSSQL
server. The following is from the Microsoft web site:
****
Pubs Sample Database

The pubs sample database is modeled after a book publishing company and
is used to demonstrate many of the options available for a Microsoft®
SQL Server™ database. The database and its tables are commonly used in
the examples presented in the documentation content.

If you have made changes to the pubs database, you can reinstall it
using files located in the Install directory of your SQL Server
installation. The installation process requires two steps:

1.  From the command prompt, use the osql utility to run the
Instpubs.sql script. This drops the existing pubs database, creates a
new one, and defines all the objects in the database.
2.  From the command prompt, run Pubimage.bat. This inserts image values
into the pub_info table.
****

=== Technical Terms

Reconcile::
  The reconcile operator adds items in the device to the Dataphor system
  catalog.

=== Libraries/Files Used

Sample.Pubs:: By registering the Sample.Pubs library, the MSSQLDevice will be
  created, the reconcile operator will be executed, and references will
  be created.
+
  CAUTION: It is assumed that the SQL server is running on the same system as the Dataphor Server.
  If this is not the case the create device expression will have to be changed before registering the library.

== Reconciliation

Reconciliation allows Dataphor to add all the items on a device to the
Dataphor system catalog. After reconciliation all the tables are
available to view and modify the data.

Catalog objects added using reconsiliation are the same as any others.
Anything that can be done to the tables and data added using
reconciliation just like those created using Dataphor.
