= Presentation Layer
:author: Alphora
:doctype: book
:data-uri:
:lang: en
:encoding: iso-8859-1

. link:PresentationOverview.adoc[Overview]
. link:PuttingItAllTogether.adoc[Putting it all Together]
. link:FormAutomation.adoc[Form Automation]
. link:SpaceBetweenData.adoc[The Space Between the Data]

[[DDGPresentationLayer]]
== Summary

This part of the Dataphor Developer's Guide focuses on the presentation
layer of Dataphor applications. It discusses presentation layer
architecture and features, as well as techniques for achieving re-use
through the application of metadata tags.

The discussions contained in this part assume a basic familiarity with
the conceptual model of application development presented in the
introductory part of this guide. In addition, the material covered in
the Logical Application Design part of the guide will be referenced
extensively.

This part of the guide is organized as follows:

* Overview
+
This chapter describes how Dataphor applications work from the Frontend
perspective. It covers the various components of the architecture that
enable the automated application development achieved by the platform,
and covers the preliminaries necessary to begin building the
presentation layer of a Dataphor application.
* Putting It All Together
+
This chapter builds the presentation layer of the Shipping application
from start to finish, providing an in-depth example of using the
Dataphor platform to build a real-world application.
* The Automation of Forms
+
This chapter discusses the process of user interface derivation in
detail, including how it can be controlled using metadata tags.
* The Space Between the Data
+
This chapter discusses three important features of the Dataphor
platform: Navigational Access, Application Transactions, and Proposable
Interfaces.

The aim of each of these chapters is to provide the
developer with an overall understanding of how the architecture enables
Automated Application Development (AAD). This understanding will in turn
help the developer take advantage of the features available in the
platform, and produce more efficient, more maintainable applications.

The running example introduced in the Logical Application Design part of
this guide will again be used as a vehicle for explaining the concepts
and techniques discussed in this part.
