= Dataphoria Web Client
:author: Alphora
:doctype: chapter
:data-uri:
:lang: en
:encoding: iso-8859-1

== Installation

The Dataphoria Web Client project was built using a template from a 3rd-party set of project templates.

http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/[Overview]

=== Dependencies

* Visual Studio 2015 Update 3. Note that Update 2 is not enough. You need Update 3, because it fixes some issues with NPM, plus it’s a prerequisite for TypeScript 2.0.
* .NET Core 1.0.1
* TypeScript 2.0 for Visual Studio 2015. If Visual Studio keeps complaining `Cannot find name 'require'`, it’s because you forgot to install this.
* Node.js version 4 or later. To check your Node version, run `node -v` in a command prompt.

While most everything should work automatically, you will have to run `webpack --config webpack.config.vendor.js` from a command line at the root of the project where the webpack.config.js file is located. 
NOTE: you must have installed webpack.

