// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>CQF.Model</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
//  <note>Changed generated class name from EntityBase<T> to Base and added XmlIncludeAttribute for immediate descendants as well as GeneratedAttributes (GeneratedCode, Serializable, DesignerCategory, XmlType, and XmlRoot</note>
// ------------------------------------------------------------------------------
namespace CQF.Model {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    #region Base entity class
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute("modelInfo", Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassInfoElement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TupleTypeInfoElement))]
    public partial class Base
    {
    }
    #endregion
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute("modelInfo", Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=false)]
    public partial class ModelInfo : Base {
        
        private List<ModelSpecifier> requiredModelInfoField;
        
        private List<TypeInfo> typeInfoField;
        
        private List<ConversionInfo> conversionInfoField;
        
        private string nameField;
        
        private string versionField;
        
        private string urlField;
        
        private string schemaLocationField;
        
        private System.Xml.XmlQualifiedName targetQualifierField;
        
        private string patientClassNameField;
        
        private string patientClassIdentifierField;
        
        private string patientBirthDatePropertyNameField;
        
        private bool caseSensitiveField;
        
        private bool caseSensitiveFieldSpecified;
        
        private bool strictRetrieveTypingField;
        
        private bool strictRetrieveTypingFieldSpecified;
        
        public ModelInfo() {
            this.conversionInfoField = new List<ConversionInfo>();
            this.typeInfoField = new List<TypeInfo>();
            this.requiredModelInfoField = new List<ModelSpecifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("requiredModelInfo")]
        public List<ModelSpecifier> requiredModelInfo {
            get {
                return this.requiredModelInfoField;
            }
            set {
                this.requiredModelInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("typeInfo")]
        public List<TypeInfo> typeInfo {
            get {
                return this.typeInfoField;
            }
            set {
                this.typeInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("conversionInfo")]
        public List<ConversionInfo> conversionInfo {
            get {
                return this.conversionInfoField;
            }
            set {
                this.conversionInfoField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemaLocation {
            get {
                return this.schemaLocationField;
            }
            set {
                this.schemaLocationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName targetQualifier {
            get {
                return this.targetQualifierField;
            }
            set {
                this.targetQualifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string patientClassName {
            get {
                return this.patientClassNameField;
            }
            set {
                this.patientClassNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string patientClassIdentifier {
            get {
                return this.patientClassIdentifierField;
            }
            set {
                this.patientClassIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string patientBirthDatePropertyName {
            get {
                return this.patientBirthDatePropertyNameField;
            }
            set {
                this.patientBirthDatePropertyNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool caseSensitive {
            get {
                return this.caseSensitiveField;
            }
            set {
                this.caseSensitiveField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool caseSensitiveSpecified {
            get {
                return this.caseSensitiveFieldSpecified;
            }
            set {
                this.caseSensitiveFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool strictRetrieveTyping {
            get {
                return this.strictRetrieveTypingField;
            }
            set {
                this.strictRetrieveTypingField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strictRetrieveTypingSpecified {
            get {
                return this.strictRetrieveTypingFieldSpecified;
            }
            set {
                this.strictRetrieveTypingFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ModelSpecifier : Base {
        
        private string nameField;
        
        private string versionField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ConversionInfo : Base {
        
        private TypeSpecifier fromTypeSpecifierField;
        
        private TypeSpecifier toTypeSpecifierField;
        
        private string functionNameField;
        
        private string fromTypeField;
        
        private string toTypeField;
        
        public TypeSpecifier fromTypeSpecifier {
            get {
                return this.fromTypeSpecifierField;
            }
            set {
                this.fromTypeSpecifierField = value;
            }
        }
        
        public TypeSpecifier toTypeSpecifier {
            get {
                return this.toTypeSpecifierField;
            }
            set {
                this.toTypeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string functionName {
            get {
                return this.functionNameField;
            }
            set {
                this.functionNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fromType {
            get {
                return this.fromTypeField;
            }
            set {
                this.fromTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toType {
            get {
                return this.toTypeField;
            }
            set {
                this.toTypeField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntervalTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamedTypeSpecifier))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public abstract partial class TypeSpecifier : Base {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ChoiceTypeSpecifier : TypeSpecifier {
        
        private List<TypeSpecifier> choiceField;
        
        public ChoiceTypeSpecifier() {
            this.choiceField = new List<TypeSpecifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("choice")]
        public List<TypeSpecifier> choice {
            get {
                return this.choiceField;
            }
            set {
                this.choiceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class IntervalTypeSpecifier : TypeSpecifier {
        
        private TypeSpecifier pointTypeSpecifierField;
        
        private string pointTypeField;
        
        public TypeSpecifier pointTypeSpecifier {
            get {
                return this.pointTypeSpecifierField;
            }
            set {
                this.pointTypeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pointType {
            get {
                return this.pointTypeField;
            }
            set {
                this.pointTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ListTypeSpecifier : TypeSpecifier {
        
        private TypeSpecifier elementTypeSpecifierField;
        
        private string elementTypeField;
        
        public TypeSpecifier elementTypeSpecifier {
            get {
                return this.elementTypeSpecifierField;
            }
            set {
                this.elementTypeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string elementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class NamedTypeSpecifier : TypeSpecifier {
        
        private string modelNameField;
        
        private string nameField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class TupleTypeInfoElement : Base {
        
        private TypeSpecifier typeSpecifierField;
        
        private string nameField;
        
        private string typeField;
        
        private bool prohibitedField;
        
        private bool prohibitedFieldSpecified;
        
        private bool oneBasedField;
        
        private bool oneBasedFieldSpecified;
        
        public TypeSpecifier typeSpecifier {
            get {
                return this.typeSpecifierField;
            }
            set {
                this.typeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool prohibited {
            get {
                return this.prohibitedField;
            }
            set {
                this.prohibitedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prohibitedSpecified {
            get {
                return this.prohibitedFieldSpecified;
            }
            set {
                this.prohibitedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool oneBased {
            get {
                return this.oneBasedField;
            }
            set {
                this.oneBasedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oneBasedSpecified {
            get {
                return this.oneBasedFieldSpecified;
            }
            set {
                this.oneBasedFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ClassInfoElement : Base {
        
        private TypeSpecifier typeSpecifierField;
        
        private string nameField;
        
        private string typeField;
        
        private bool prohibitedField;
        
        private bool prohibitedFieldSpecified;
        
        private bool oneBasedField;
        
        private bool oneBasedFieldSpecified;
        
        public TypeSpecifier typeSpecifier {
            get {
                return this.typeSpecifierField;
            }
            set {
                this.typeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool prohibited {
            get {
                return this.prohibitedField;
            }
            set {
                this.prohibitedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prohibitedSpecified {
            get {
                return this.prohibitedFieldSpecified;
            }
            set {
                this.prohibitedFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool oneBased {
            get {
                return this.oneBasedField;
            }
            set {
                this.oneBasedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oneBasedSpecified {
            get {
                return this.oneBasedFieldSpecified;
            }
            set {
                this.oneBasedFieldSpecified = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TupleTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntervalTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public abstract partial class TypeInfo : Base {
        
        private TypeSpecifier baseTypeSpecifierField;
        
        private string baseTypeField;
        
        public TypeSpecifier baseTypeSpecifier {
            get {
                return this.baseTypeSpecifierField;
            }
            set {
                this.baseTypeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string baseType {
            get {
                return this.baseTypeField;
            }
            set {
                this.baseTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ChoiceTypeInfo : TypeInfo {
        
        private List<TypeSpecifier> typeField;
        
        public ChoiceTypeInfo() {
            this.typeField = new List<TypeSpecifier>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public List<TypeSpecifier> type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class TupleTypeInfo : TypeInfo {
        
        private List<TupleTypeInfoElement> elementField;
        
        public TupleTypeInfo() {
            this.elementField = new List<TupleTypeInfoElement>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("element")]
        public List<TupleTypeInfoElement> element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ListTypeInfo : TypeInfo {
        
        private TypeSpecifier elementTypeSpecifierField;
        
        private string elementTypeField;
        
        public TypeSpecifier elementTypeSpecifier {
            get {
                return this.elementTypeSpecifierField;
            }
            set {
                this.elementTypeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string elementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class IntervalTypeInfo : TypeInfo {
        
        private TypeSpecifier pointTypeSpecifierField;
        
        private string pointTypeField;
        
        public TypeSpecifier pointTypeSpecifier {
            get {
                return this.pointTypeSpecifierField;
            }
            set {
                this.pointTypeSpecifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pointType {
            get {
                return this.pointTypeField;
            }
            set {
                this.pointTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class SimpleTypeInfo : TypeInfo {
        
        private string nameField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ClassInfo : TypeInfo {
        
        private List<ClassInfoElement> elementField;
        
        private string nameField;
        
        private string identifierField;
        
        private string labelField;
        
        private bool retrievableField;
        
        private string primaryCodePathField;
        
        public ClassInfo() {
            this.elementField = new List<ClassInfoElement>();
            this.retrievableField = false;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("element")]
        public List<ClassInfoElement> element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool retrievable {
            get {
                return this.retrievableField;
            }
            set {
                this.retrievableField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string primaryCodePath {
            get {
                return this.primaryCodePathField;
            }
            set {
                this.primaryCodePathField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.32990")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:hl7-org:elm-modelinfo:r1", IsNullable=true)]
    public partial class ProfileInfo : ClassInfo {
    }
}
