//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alphora.Dataphor.Frontend.Client.Windows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alphora.Dataphor.Frontend.Client.Windows.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;ccept.
        /// </summary>
        internal static string AcceptButtonText {
            get {
                return ResourceManager.GetString("AcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string AcceptMenuText {
            get {
                return ResourceManager.GetString("AcceptMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advanced &gt;&gt;.
        /// </summary>
        internal static string CAdvancedButton {
            get {
                return ResourceManager.GetString("CAdvancedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Basic &lt;&lt;.
        /// </summary>
        internal static string CBasicButton {
            get {
                return ResourceManager.GetString("CBasicButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Server Alias.
        /// </summary>
        internal static string CConfirmAliasDeleteCaption {
            get {
                return ResourceManager.GetString("CConfirmAliasDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this Server Alias?.
        /// </summary>
        internal static string CConfirmAliasDeleteText {
            get {
                return ResourceManager.GetString("CConfirmAliasDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string CConnectedText {
            get {
                return ResourceManager.GetString("CConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to device (ensure device is attached and ready for capture)..
        /// </summary>
        internal static string CConnectionErrorText {
            get {
                return ResourceManager.GetString("CConnectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title.
        /// </summary>
        internal static string CDefaultNotebookPageTitle {
            get {
                return ResourceManager.GetString("CDefaultNotebookPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string CFrameDefaultMenuText {
            get {
                return ResourceManager.GetString("CFrameDefaultMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; &amp;Details.
        /// </summary>
        internal static string CLessDetails {
            get {
                return ResourceManager.GetString("CLessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CloseMenuText {
            get {
                return ResourceManager.GetString("CloseMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details &gt;&gt;.
        /// </summary>
        internal static string CMoreDetails {
            get {
                return ResourceManager.GetString("CMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataphor.ImageCapture.bmp.
        /// </summary>
        internal static string CTempFileName {
            get {
                return ResourceManager.GetString("CTempFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ctrl-Tab] to Continue.
        /// </summary>
        internal static string CtrlTabToContinue {
            get {
                return ResourceManager.GetString("CtrlTabToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter] to Continue.
        /// </summary>
        internal static string EnterToContinue {
            get {
                return ResourceManager.GetString("EnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter] to {0}.
        /// </summary>
        internal static string EnterToDefault {
            get {
                return ResourceManager.GetString("EnterToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F9] to {0}.
        /// </summary>
        internal static string F9ToDefault {
            get {
                return ResourceManager.GetString("F9ToDefault", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NoPhoto {
            get {
                object obj = ResourceManager.GetObject("NoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reject.
        /// </summary>
        internal static string RejectButtonText {
            get {
                return ResourceManager.GetString("RejectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reject.
        /// </summary>
        internal static string RejectMenuText {
            get {
                return ResourceManager.GetString("RejectMenuText", resourceCulture);
            }
        }
    }
}
